name: emergency_buddy
description: "A new Flutter project to demonstrate the usage of on device AI models."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # pub-dev dependencies
  flutter_gemma: ^0.10.0 # The most important dependency

  image_picker: ^1.0.4
  flutter_markdown: ^0.7.1
  url_launcher: ^6.3.1
  http: ^1.3.0
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3
  injectable: ^2.5.1
  get_it: ^8.0.3
  geolocator: ^14.0.2
  connectivity_plus: ^6.1.4
  network_info_plus: ^6.1.4
  geocoding: ^4.0.0
  flutter_bloc: ^9.1.1
  provider: ^6.1.5
  freezed: ^3.2.0
  freezed_annotation: ^3.1.0
  fuzzywuzzy: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  injectable_generator: ^2.5.1
  build_runner: ^2.6.0
  json_serializable: ^6.10.0

flutter:
  uses-material-design: true

  assets:
    - assets/gemma/
    - assets/data/first_aid_categories.json
    - assets/data/listing.json
    - assets/data/knowledge_graph.json
    - assets/data/pdf.json
    - assets/pdf/

first_aid_categories:
  dart:
